version: "3.8"

services:
  app:
    image: wishosz/redesii:latest
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: redes
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: redes
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: