version: "3.8"

services:
  app:
    image: wishosz/redesii:latest
    container_name: redesii_app_prod
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost
      APP_KEY: "base64:9poqzaGDIlEny37zR121+xwk2hW0KRHyyMFw7102ZHw="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: redes
      DB_USERNAME: root
      DB_PASSWORD: ""
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: redesii_db_prod
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: redes
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: